#!/bin/sh
commit_msg=$(cat "$1")
pattern='^.*(feat|fix|docs|chore|style|refactor|test|perf|build|ci|revert)(\([a-z0-9-]+\))?: .+'

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "❌ Commit inválido. Formato esperado: <emoji> <type>(<scope>): <description>"
  echo "   Tipos válidos: feat|fix|docs|chore|style|refactor|test|perf"
  echo "   Exemplo: ✨ feat(ws): add room isolation"
  exit 1
fi
